--
-- PostgreSQL database dump
--

\restrict VWCfOMaTwqXJ1bX6ccW5ZwDOawZ94lTeMlGW7XxiHTlPhfbQM4DdwLgD9gSq7TL

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: handle_new_user(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.handle_new_user() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    AS $$
DECLARE
    -- Ambil username dari email
    -- Contoh: admin@kopi9.local -> admin
    v_username TEXT := split_part(NEW.email, '@', 1);
BEGIN

    -- Jika username sudah ada di public.users
    IF EXISTS (
        SELECT 1
        FROM public.users
        WHERE username = v_username
    ) THEN

        -- Hubungkan akun Auth dengan user yang sudah ada
        UPDATE public.users
        SET auth_id = NEW.id
        WHERE username = v_username;

    ELSE

        -- Jika user benar-benar baru, buat record baru
        INSERT INTO public.users (
            auth_id,
            username,
            name,
            role,
            active
        )
        VALUES (
            NEW.id,
            v_username,
            COALESCE(
                NEW.raw_user_meta_data->>'name',
                v_username
            ),
            COALESCE(
                NEW.raw_user_meta_data->>'role',
                'kasir'
            ),
            true
        );

    END IF;

    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_logs (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    user_id text,
    user_name text NOT NULL,
    user_role text NOT NULL,
    action text NOT NULL,
    details text
);


--
-- Name: activity_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.categories (
    id integer NOT NULL,
    name text NOT NULL,
    color text,
    icon text,
    created_at timestamp with time zone DEFAULT now()
);


--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.categories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: categories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.categories_id_seq OWNED BY public.categories.id;


--
-- Name: product_variants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_variants (
    id integer NOT NULL,
    product_id integer,
    group_name text NOT NULL,
    name text NOT NULL,
    price_modifier integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


--
-- Name: product_variants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.product_variants_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: product_variants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.product_variants_id_seq OWNED BY public.product_variants.id;


--
-- Name: products; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.products (
    id integer NOT NULL,
    name text NOT NULL,
    base_price integer NOT NULL,
    category text NOT NULL,
    emoji text,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);


--
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.products_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: products_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.products_id_seq OWNED BY public.products.id;


--
-- Name: settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settings (
    key text NOT NULL,
    value jsonb NOT NULL
);


--
-- Name: transaction_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaction_items (
    id integer NOT NULL,
    transaction_id text,
    product_id integer,
    qty integer NOT NULL,
    price integer NOT NULL,
    selected_variants jsonb,
    item_note text
);


--
-- Name: transaction_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.transaction_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: transaction_items_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.transaction_items_id_seq OWNED BY public.transaction_items.id;


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transactions (
    id text NOT NULL,
    date timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    customer_phone text,
    total integer NOT NULL,
    payment_method text NOT NULL,
    payment_status text DEFAULT 'Lunas'::text NOT NULL,
    notes text,
    cashier_name text NOT NULL,
    cash_amount numeric DEFAULT 0,
    cash_change numeric DEFAULT 0
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    name text NOT NULL,
    username text NOT NULL,
    password_hash text NOT NULL,
    role text DEFAULT 'kasir'::text NOT NULL,
    active boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    auth_id uuid
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: categories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories ALTER COLUMN id SET DEFAULT nextval('public.categories_id_seq'::regclass);


--
-- Name: product_variants id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants ALTER COLUMN id SET DEFAULT nextval('public.product_variants_id_seq'::regclass);


--
-- Name: products id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products ALTER COLUMN id SET DEFAULT nextval('public.products_id_seq'::regclass);


--
-- Name: transaction_items id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_items ALTER COLUMN id SET DEFAULT nextval('public.transaction_items_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: activity_logs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.activity_logs (id, created_at, user_id, user_name, user_role, action, details) FROM stdin;
1	2026-05-30 04:33:58.073007+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
2	2026-05-30 04:34:55.305228+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
3	2026-05-30 04:43:18.863436+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
4	2026-05-30 04:43:59.716004+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260530-4599, Total: Rp 56.000
5	2026-05-30 04:44:21.137744+00	1	Admin Utama	admin	Edit Transaksi	ID: TXN-20260530-4599, Status: Lunas, Metode: cash
6	2026-05-30 05:32:26.855113+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
7	2026-05-30 05:32:59.884298+00	2	Kasir	kasir	Login Berhasil	User Kasir masuk ke sistem
8	2026-05-30 05:50:29.154221+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
9	2026-05-30 11:24:24.146107+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
10	2026-06-02 01:41:13.199217+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
11	2026-06-02 04:22:56.790029+00	1	Admin Utama	admin	Tambah Produk	Nama: Burnt Cheese Cake, Kategori: Non-Coffee, Harga: Rp 23.000
12	2026-06-02 04:23:27.75752+00	1	Admin Utama	admin	Tambah Produk	Nama: Tiramisu Salted Caramel, Kategori: Non-Coffee, Harga: Rp 25.000
13	2026-06-02 04:23:49.046072+00	1	Admin Utama	admin	Tambah Produk	Nama: Tiramisu Cookies n' Cream, Kategori: Non-Coffee, Harga: Rp 25.000
14	2026-06-02 04:24:02.448206+00	1	Admin Utama	admin	Tambah Produk	Nama: Dubai Chewy Cookie, Kategori: Non-Coffee, Harga: Rp 23.000
15	2026-06-02 04:24:15.032646+00	1	Admin Utama	admin	Tambah Produk	Nama: Cuanki, Kategori: Non-Coffee, Harga: Rp 18.000
16	2026-06-02 04:33:55.489088+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
17	2026-06-02 04:38:55.271785+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-7680, Total: Rp 48.000
18	2026-06-02 04:44:29.041018+00	2	Kasir	kasir	Login Berhasil	User Kasir masuk ke sistem
19	2026-06-02 04:45:07.364428+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-8811, Total: Rp 86.000
20	2026-06-02 05:21:22.233059+00	1	Admin Utama	admin	Tambah Produk	Nama: Filter, Kategori: Specialty Coffee, Harga: Rp 45.000
21	2026-06-02 05:25:19.106109+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
22	2026-06-02 05:25:48.477315+00	1	Admin Utama	admin	Tambah Produk	Nama: Test, Kategori: Specialty Coffee, Harga: Rp 10
23	2026-06-02 05:25:56.074497+00	1	Admin Utama	admin	Hapus Produk	ID: 48
24	2026-06-02 05:27:15.191891+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-7770, Total: Rp 41.000
25	2026-06-02 05:27:43.03942+00	1	Admin Utama	admin	Edit Transaksi	ID: TXN-20260602-7770, Status: Lunas, Metode: qris
26	2026-06-02 05:30:13.458215+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
27	2026-06-02 05:53:57.532988+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-6712, Total: Rp 131.000
28	2026-06-02 05:54:51.471645+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-1933, Total: Rp 83.000
29	2026-06-02 06:05:16.416269+00	1	Admin Utama	admin	Update Info Toko	Nama: Toko Kopi Sembilan
30	2026-06-02 06:16:38.03658+00	1	Admin Utama	admin	Tambah Produk	Nama: Padma 100gr, Kategori: Beans, Harga: Rp 78.000
31	2026-06-02 06:16:38.210726+00	1	Admin Utama	admin	Tambah Produk	Nama: Padma 100gr, Kategori: Beans, Harga: Rp 78.000
32	2026-06-02 06:17:28.085969+00	1	Admin Utama	admin	Tambah Produk	Nama: Maresa 100gr, Kategori: Beans, Harga: Rp 78.000
33	2026-06-02 06:17:46.449035+00	1	Admin Utama	admin	Tambah Produk	Nama: Nayara 100gr, Kategori: Beans, Harga: Rp 70.000
34	2026-06-02 06:18:07.540705+00	1	Admin Utama	admin	Tambah Produk	Nama: Pusporeso 100gr, Kategori: Beans, Harga: Rp 68.000
35	2026-06-02 06:18:22.676334+00	1	Admin Utama	admin	Tambah Produk	Nama: Velania 100gr, Kategori: Beans, Harga: Rp 78.000
36	2026-06-02 06:18:39.966531+00	1	Admin Utama	admin	Tambah Produk	Nama: Arumpala 100gr, Kategori: Beans, Harga: Rp 76.000
37	2026-06-02 06:19:04.577524+00	1	Admin Utama	admin	Tambah Produk	Nama: Rayana 500gr, Kategori: Beans, Harga: Rp 167.000
38	2026-06-02 06:19:05.344165+00	1	Admin Utama	admin	Tambah Produk	Nama: Rayana 500gr, Kategori: Beans, Harga: Rp 167.000
39	2026-06-02 06:19:24.739421+00	1	Admin Utama	admin	Tambah Produk	Nama: Rayana 1kg, Kategori: Beans, Harga: Rp 345.000
40	2026-06-02 06:20:14.293826+00	1	Admin Utama	admin	Tambah Produk	Nama: Damara 500gr, Kategori: Beans, Harga: Rp 80.000
41	2026-06-02 06:20:27.522957+00	1	Admin Utama	admin	Tambah Produk	Nama: Damara 1kg, Kategori: Beans, Harga: Rp 148.000
42	2026-06-02 06:21:01.570157+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-6579, Total: Rp 30.000
43	2026-06-02 06:21:01.852642+00	1	Admin Utama	admin	Tambah Produk	Nama: Arum Lathi 100gr, Kategori: Beans, Harga: Rp 82.000
44	2026-06-02 06:39:34.020533+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4137, Total: Rp 28.000
45	2026-06-02 06:57:23.177936+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-1011, Total: Rp 50.000
46	2026-06-02 07:37:06.508109+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-9031, Total: Rp 161.000
47	2026-06-02 07:38:52.316017+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4377, Total: Rp 15.000
48	2026-06-02 07:40:32.003577+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-8454, Total: Rp 25.000
49	2026-06-02 08:01:21.472309+00	2	Kasir	kasir	Edit Transaksi	ID: TXN-20260602-9031, Status: Belum Bayar, Metode: qris
50	2026-06-02 08:35:16.265048+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-2976, Total: Rp 98.000
51	2026-06-02 08:41:56.551219+00	2	Kasir	kasir	Edit Transaksi	ID: TXN-20260602-9031, Status: Belum Bayar, Metode: qris
52	2026-06-02 08:43:25.160416+00	2	Kasir	kasir	Edit Transaksi	ID: TXN-20260602-9031, Status: Belum Bayar, Metode: qris
53	2026-06-02 08:43:33.742404+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-9285, Total: Rp 116.000
54	2026-06-02 08:45:28.922171+00	1	Admin Utama	admin	Edit Transaksi	ID: TXN-20260602-9031, Status: Lunas, Metode: qris
55	2026-06-02 08:45:43.531702+00	1	Admin Utama	admin	Edit Transaksi	ID: TXN-20260602-9285, Status: Lunas, Metode: qris
56	2026-06-02 08:47:21.641123+00	2	Kasir	kasir	Edit Transaksi	ID: TXN-20260602-9031, Status: Lunas, Metode: qris
57	2026-06-02 08:48:54.617942+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-2528, Total: Rp 28.000
58	2026-06-02 08:59:11.459171+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-2625, Total: Rp 50.000
59	2026-06-02 09:09:02.68665+00	1	Admin Utama	admin	Edit Produk	Nama: Dubai Chewy Cookie, Kategori: Dessert, Harga: Rp 23.000
60	2026-06-02 09:09:22.89344+00	1	Admin Utama	admin	Edit Produk	Nama: Tiramisu Cookies n' Cream, Kategori: Dessert, Harga: Rp 25.000
61	2026-06-02 09:09:31.785381+00	1	Admin Utama	admin	Edit Produk	Nama: Tiramisu Salted Caramel, Kategori: Dessert, Harga: Rp 25.000
62	2026-06-02 09:09:38.909514+00	1	Admin Utama	admin	Edit Produk	Nama: Burnt Cheese Cake, Kategori: Dessert, Harga: Rp 23.000
63	2026-06-02 09:10:37.957733+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-6595, Total: Rp 71.000
64	2026-06-02 09:11:22.668304+00	1	Admin Utama	admin	Edit Produk	Nama: Cuanki, Kategori: Snack, Harga: Rp 18.000
65	2026-06-02 09:16:30.8251+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-9930, Total: Rp 81.000
66	2026-06-02 09:17:19.078252+00	1	Admin Utama	admin	Edit Transaksi	ID: TXN-20260602-2625, Status: Lunas, Metode: qris
67	2026-06-02 09:53:45.229621+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-3027, Total: Rp 43.000
68	2026-06-02 09:58:22.79145+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-3045, Total: Rp 28.000
69	2026-06-02 10:09:34.928546+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-2195, Total: Rp 51.000
70	2026-06-02 10:14:24.660145+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-8298, Total: Rp 33.000
71	2026-06-02 10:26:45.75022+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-3421, Total: Rp 36.000
72	2026-06-02 10:50:37.370828+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-3873, Total: Rp 36.000
73	2026-06-02 10:50:37.665139+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-5674, Total: Rp 36.000
74	2026-06-02 11:02:28.768652+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4918, Total: Rp 30.000
75	2026-06-02 11:03:02.566481+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-1554, Total: Rp 51.000
76	2026-06-02 11:04:21.817873+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4567, Total: Rp 28.000
77	2026-06-02 11:11:09.407054+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4139, Total: Rp 28.000
78	2026-06-02 11:20:18.506572+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4541, Total: Rp 94.000
79	2026-06-02 11:20:18.734564+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-5190, Total: Rp 94.000
80	2026-06-02 11:44:12.462833+00	1	Admin Utama	admin	Tambah Produk	Nama: Filter, Kategori: Specialty Coffee, Harga: Rp 35.000
81	2026-06-02 11:53:25.048514+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-1612, Total: Rp 78.000
82	2026-06-02 11:55:46.749837+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-1123, Total: Rp 46.000
83	2026-06-02 12:14:03.896371+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-1760, Total: Rp 83.000
84	2026-06-02 12:20:28.698907+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-5453, Total: Rp 140.000
85	2026-06-02 12:20:29.101535+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-5318, Total: Rp 140.000
86	2026-06-02 12:42:13.686434+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-5272, Total: Rp 23.000
87	2026-06-02 12:42:14.069959+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-2531, Total: Rp 23.000
88	2026-06-02 12:58:57.63896+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-2010, Total: Rp 23.000
89	2026-06-02 13:16:03.538476+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-2711, Total: Rp 94.000
90	2026-06-02 13:45:12.298172+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-5783, Total: Rp 60.000
91	2026-06-02 14:49:14.910874+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-7750, Total: Rp 68.000
92	2026-06-02 15:08:32.638809+00	2	Kasir	kasir	Transaksi Baru	ID: TXN-20260602-4843, Total: Rp 54.000
93	2026-06-02 15:46:26.6763+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
94	2026-06-02 22:32:41.656326+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-4411, Total: Rp 33.000
95	2026-06-02 22:33:06.729157+00	1	Admin Utama	admin	Hapus Transaksi	ID: TXN-20260602-4411
96	2026-06-02 22:37:31.741193+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-9538, Total: Rp 68.000
97	2026-06-02 22:37:57.351224+00	1	Admin Utama	admin	Edit Transaksi & Pesanan	ID: TXN-20260602-9538, Total Baru: Rp 0
98	2026-06-02 22:38:09.570324+00	1	Admin Utama	admin	Hapus Transaksi	ID: TXN-20260602-9538
99	2026-06-02 22:43:55.860534+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-5013, Total: Rp 76.000
100	2026-06-02 22:44:25.555655+00	1	Admin Utama	admin	Update Transaksi	ID: TXN-20260602-5013, Total: Rp 124.000
101	2026-06-02 22:44:43.481405+00	1	Admin Utama	admin	Edit Transaksi & Pesanan	ID: TXN-20260602-5013, Total Baru: Rp 0
102	2026-06-02 22:45:01.395345+00	1	Admin Utama	admin	Hapus Transaksi	ID: TXN-20260602-5013
103	2026-06-02 22:47:43.608405+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-9575, Total: Rp 63.000
104	2026-06-02 22:48:18.626542+00	1	Admin Utama	admin	Edit Transaksi & Pesanan	ID: TXN-20260602-9575, Total Baru: Rp 0
105	2026-06-02 22:48:27.328087+00	1	Admin Utama	admin	Hapus Transaksi	ID: TXN-20260602-9575
106	2026-06-02 22:49:32.050121+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-4262, Total: Rp 50.000
107	2026-06-02 22:49:41.466639+00	1	Admin Utama	admin	Edit Transaksi & Pesanan	ID: TXN-20260602-4262, Total Baru: Rp 50.000
108	2026-06-02 22:49:59.795725+00	1	Admin Utama	admin	Update Transaksi	ID: TXN-20260602-4262, Total: Rp 126.000
109	2026-06-02 22:50:11.095223+00	1	Admin Utama	admin	Hapus Transaksi	ID: TXN-20260602-4262
110	2026-06-02 22:52:35.157634+00	1	Admin Utama	admin	Backup Sistem	Unduh file JSON backup manual
111	2026-06-02 23:37:53.597318+00	1	Admin Utama	admin	Login Berhasil	User Admin Utama masuk ke sistem
112	2026-06-02 23:44:42.595783+00	1	Admin Utama	admin	Transaksi Baru	ID: TXN-20260602-7142, Total: Rp 71.000
113	2026-06-02 23:44:58.245498+00	1	Admin Utama	admin	Update Transaksi	ID: TXN-20260602-7142, Total: Rp 109.000
114	2026-06-02 23:45:03.261318+00	1	Admin Utama	admin	Hapus Transaksi	ID: TXN-20260602-7142
\.


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.categories (id, name, color, icon, created_at) FROM stdin;
1	Specialty Coffee	#D4A05A	coffee	2026-06-02 05:48:51.052597+00
2	Regular Coffee	#8B5320	coffee	2026-06-02 05:48:51.052597+00
3	Non-Coffee	#C8602A	cup-soda	2026-06-02 05:48:51.052597+00
4	Signature	#2D5A27	glass-water	2026-06-02 05:48:51.052597+00
8	Beans	#6b3f1a	coffee	2026-06-02 05:57:13.900113+00
9	Dessert	#ff0084	dessert	2026-06-02 09:07:59.404036+00
10	Snack	#ffd900	pizza	2026-06-02 09:11:07.573245+00
\.


--
-- Data for Name: product_variants; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.product_variants (id, product_id, group_name, name, price_modifier, created_at) FROM stdin;
\.


--
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.products (id, name, base_price, category, emoji, active, created_at) FROM stdin;
1	Americano - Specialty	28000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
2	Espresso - Specialty	28000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
3	Latte - Specialty	33000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
4	Cappuccino - Specialty	33000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
5	Split - Specialty	38000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
6	Dirty - Specialty	38000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
7	Magic - Specialty	38000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
8	Filter Coffee	30000	Specialty Coffee	coffee	t	2026-05-29 02:27:07.823668+00
9	Americano - Regular	15000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
10	Espresso - Regular	15000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
11	Hazelnut - Regular	25000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
12	Gula Aren - Regular	25000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
13	Butterscotch - Regular	28000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
14	Vanilla - Regular	25000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
15	Caramel - Regular	25000	Regular Coffee	coffee	t	2026-05-29 02:27:07.823668+00
16	Kopi Susu Sembilan	18000	Regular Coffee	drink	t	2026-05-29 02:27:07.823668+00
17	Matcha U	28000	Non-Coffee	drink	t	2026-05-29 02:27:07.823668+00
18	Get Red Velvet	23000	Non-Coffee	drink	t	2026-05-29 02:27:07.823668+00
19	Cookie Me	23000	Non-Coffee	drink	t	2026-05-29 02:27:07.823668+00
20	Coklat	25000	Non-Coffee	drink	t	2026-05-29 02:27:07.823668+00
21	Summer Tea	18000	Non-Coffee	drink	t	2026-05-29 02:27:07.823668+00
22	Tropik Tea	20000	Non-Coffee	drink	t	2026-05-29 02:27:07.823668+00
23	St. Mocktail	25000	Signature	drink	t	2026-05-29 02:27:07.823668+00
24	Cocoa Rum	28000	Signature	drink	t	2026-05-29 02:27:07.823668+00
25	The Palma	25000	Signature	drink	t	2026-05-29 02:27:07.823668+00
28	Filter v40	50000	Specialty Coffee	\N	f	2026-05-29 03:30:07.582093+00
29	Filter v40	50000	Specialty Coffee	\N	f	2026-05-29 03:34:42.680741+00
30	a	65000	Specialty Coffee	\N	f	2026-05-29 03:39:27.452013+00
31	a	50000	Specialty Coffee	\N	f	2026-05-29 03:41:22.795017+00
32	a	600	Specialty Coffee	\N	f	2026-05-29 03:55:32.656849+00
33	a	50000	Specialty Coffee	\N	f	2026-05-29 06:07:08.499333+00
34	a	100000	Specialty Coffee	\N	f	2026-05-29 12:35:58.687971+00
35	a	50000	Specialty Coffee	\N	f	2026-05-29 12:55:44.985281+00
36	a	10000	Specialty Coffee	\N	f	2026-05-29 13:09:51.888588+00
26	Starlett	25000	Signature	drink	t	2026-05-29 02:27:07.823668+00
47	Filter	45000	Specialty Coffee	\N	t	2026-06-02 05:21:21.714049+00
48	Test	10	Specialty Coffee	\N	f	2026-06-02 05:25:48.323152+00
49	Padma 100gr	78000	Beans	\N	t	2026-06-02 06:16:37.783554+00
50	Padma 100gr	78000	Beans	\N	t	2026-06-02 06:16:37.808242+00
51	Maresa 100gr	78000	Beans	\N	t	2026-06-02 06:17:27.534557+00
52	Nayara 100gr	70000	Beans	\N	t	2026-06-02 06:17:46.194494+00
53	Pusporeso 100gr	68000	Beans	\N	t	2026-06-02 06:18:07.243229+00
54	Velania 100gr	78000	Beans	\N	t	2026-06-02 06:18:22.493997+00
55	Arumpala 100gr	76000	Beans	\N	t	2026-06-02 06:18:39.776052+00
56	Rayana 500gr	167000	Beans	\N	t	2026-06-02 06:19:04.161063+00
57	Rayana 500gr	167000	Beans	\N	t	2026-06-02 06:19:04.982909+00
58	Rayana 1kg	345000	Beans	\N	t	2026-06-02 06:19:24.556236+00
59	Damara 500gr	80000	Beans	\N	t	2026-06-02 06:20:13.927225+00
60	Damara 1kg	148000	Beans	\N	t	2026-06-02 06:20:27.284695+00
61	Arum Lathi 100gr	82000	Beans	\N	t	2026-06-02 06:21:01.247256+00
45	Dubai Chewy Cookie	23000	Dessert	\N	t	2026-06-02 04:24:02.23256+00
44	Tiramisu Cookies n' Cream	25000	Dessert	\N	t	2026-06-02 04:23:48.83669+00
43	Tiramisu Salted Caramel	25000	Dessert	\N	t	2026-06-02 04:23:27.594146+00
42	Burnt Cheese Cake	23000	Dessert	\N	t	2026-06-02 04:22:56.321515+00
46	Cuanki	18000	Snack	\N	t	2026-06-02 04:24:14.826582+00
62	Filter	35000	Specialty Coffee	\N	t	2026-06-02 11:44:12.23881+00
\.


--
-- Data for Name: settings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.settings (key, value) FROM stdin;
wa_template	"*INVOICE [NAMA_TOKO]*\\nJl. Pemuda Kutorejo Gg. II No.230, Kutorejo, Tuban, Jawa Timur 62311\\nID: [ID_TXN]\\nTanggal: [TANGGAL]\\n----------------------------\\n[ITEMS]\\n----------------------------\\n*TOTAL: [TOTAL]*\\n\\nTerima kasih sudah memesan!"
store_info	{"name": "Toko Kopi Sembilan", "phone": "085336688839", "address": "Jl. Pemuda Kutorejo Gg. II No.230, Kutorejo, Kec. Tuban, Kabupaten Tuban, Jawa Timur 62311"}
\.


--
-- Data for Name: transaction_items; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transaction_items (id, transaction_id, product_id, qty, price, selected_variants, item_note) FROM stdin;
5	TXN-20260602-8811	6	1	38000	[]	
6	TXN-20260602-8811	42	1	23000	[]	
7	TXN-20260602-8811	15	1	25000	[]	
10	TXN-20260602-6712	8	1	30000	[]	
11	TXN-20260602-6712	47	1	45000	[]	
12	TXN-20260602-6712	42	1	23000	[]	
13	TXN-20260602-6712	3	1	33000	[]	
14	TXN-20260602-1933	8	1	30000	[]	
15	TXN-20260602-1933	12	1	25000	[]	
16	TXN-20260602-1933	13	1	28000	[]	
17	TXN-20260602-6579	8	1	30000	[]	
18	TXN-20260602-4137	24	1	28000	[]	
19	TXN-20260602-1011	20	1	25000	[]	
20	TXN-20260602-1011	20	1	25000	[]	
21	TXN-20260602-9031	8	1	30000	[]	
22	TXN-20260602-9031	15	2	25000	[]	
23	TXN-20260602-9031	3	1	33000	[]	
24	TXN-20260602-9031	43	1	25000	[]	
25	TXN-20260602-9031	42	1	23000	[]	
26	TXN-20260602-4377	9	1	15000	[]	
27	TXN-20260602-8454	12	1	25000	[]	
28	TXN-20260602-2976	12	1	25000	[]	
29	TXN-20260602-2976	12	1	25000	[]	
30	TXN-20260602-2976	19	1	23000	[]	
31	TXN-20260602-2976	43	1	25000	[]	
32	TXN-20260602-9285	3	1	33000	[]	
33	TXN-20260602-9285	8	1	30000	[]	
34	TXN-20260602-9285	13	1	28000	[]	
35	TXN-20260602-9285	12	1	25000	[]	
36	TXN-20260602-2528	1	1	28000	[]	
37	TXN-20260602-2625	12	1	25000	[]	
38	TXN-20260602-2625	11	1	25000	[]	
39	TXN-20260602-6595	13	1	28000	[]	
40	TXN-20260602-6595	43	1	25000	[]	
41	TXN-20260602-6595	16	1	18000	[]	
42	TXN-20260602-9930	42	1	23000	[]	
43	TXN-20260602-9930	12	1	25000	[]	
44	TXN-20260602-9930	4	1	33000	[]	
45	TXN-20260602-3027	16	1	18000	[]	
46	TXN-20260602-3027	11	1	25000	[]	
47	TXN-20260602-3045	13	1	28000	[]	
48	TXN-20260602-2195	42	1	23000	[]	
49	TXN-20260602-2195	13	1	28000	[]	
50	TXN-20260602-8298	3	1	33000	[]	
51	TXN-20260602-3421	16	1	18000	[]	
52	TXN-20260602-3421	16	1	18000	[]	
53	TXN-20260602-3873	16	1	18000	[]	
54	TXN-20260602-3873	16	1	18000	[]	
55	TXN-20260602-4918	8	1	30000	[]	
56	TXN-20260602-1554	1	1	28000	[]	
57	TXN-20260602-1554	42	1	23000	[]	
58	TXN-20260602-4567	1	1	28000	[]	
59	TXN-20260602-4139	13	1	28000	[]	
60	TXN-20260602-4541	20	1	25000	[]	
61	TXN-20260602-4541	19	1	23000	[]	
62	TXN-20260602-4541	42	1	23000	[]	
63	TXN-20260602-4541	42	1	23000	[]	
68	TXN-20260602-1612	11	1	25000	[]	
69	TXN-20260602-1612	15	1	25000	[]	
70	TXN-20260602-1612	13	1	28000	[]	
71	TXN-20260602-1123	19	1	23000	[]	
72	TXN-20260602-1123	18	1	23000	[]	
73	TXN-20260602-1760	4	1	33000	[]	
74	TXN-20260602-1760	11	1	25000	[]	
75	TXN-20260602-1760	11	1	25000	[]	
76	TXN-20260602-5453	8	1	30000	[]	
77	TXN-20260602-5453	8	1	30000	[]	
78	TXN-20260602-5453	8	1	30000	[]	
79	TXN-20260602-5453	44	1	25000	[]	
80	TXN-20260602-5453	43	1	25000	[]	
81	TXN-20260602-5272	18	1	23000	[]	
82	TXN-20260602-2010	42	1	23000	[]	
83	TXN-20260602-2711	18	1	23000	[]	
84	TXN-20260602-2711	19	1	23000	[]	
85	TXN-20260602-2711	19	1	23000	[]	
86	TXN-20260602-2711	20	1	25000	[]	
87	TXN-20260602-5783	8	1	30000	[]	
88	TXN-20260602-5783	8	1	30000	[]	
89	TXN-20260602-7750	16	1	18000	[]	
90	TXN-20260602-7750	12	1	25000	[]	
91	TXN-20260602-7750	11	1	25000	[]	
92	TXN-20260602-4843	16	1	18000	[]	
93	TXN-20260602-4843	16	1	18000	[]	
94	TXN-20260602-4843	16	1	18000	[]	
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.transactions (id, date, customer_phone, total, payment_method, payment_status, notes, cashier_name, cash_amount, cash_change) FROM stdin;
TXN-20260602-8811	2026-06-02 04:45:06.794479+00		86000	qris	Lunas		Kasir	0	0
TXN-20260602-6712	2026-06-02 05:53:56.999263+00		131000	qris	Lunas		Kasir	0	0
TXN-20260602-1933	2026-06-02 05:54:51.07503+00		83000	cash	Lunas		Kasir	83000	0
TXN-20260602-6579	2026-06-02 06:21:01.201236+00		30000	qris	Lunas		Kasir	0	0
TXN-20260602-4137	2026-06-02 06:39:33.577646+00		28000	qris	Lunas		Kasir	0	0
TXN-20260602-1011	2026-06-02 06:57:22.72014+00		50000	cash	Lunas		Kasir	50000	0
TXN-20260602-4377	2026-06-02 07:38:51.854739+00		15000	qris	Lunas		Kasir	0	0
TXN-20260602-8454	2026-06-02 07:40:31.452193+00	085336688839	25000	qris	Lunas		Kasir	0	0
TXN-20260602-2976	2026-06-02 08:35:15.518736+00		98000	qris	Lunas		Kasir	0	0
TXN-20260602-9285	2026-06-02 08:43:33.349634+00		116000	qris	Lunas		Admin Utama	0	0
TXN-20260602-9031	2026-06-02 07:37:05.798724+00		161000	qris	Lunas	tambahan orderan\nlatte ice 1\nfilter padma 1\nbuterscot 1\ngula aren 1	Kasir	0	0
TXN-20260602-2528	2026-06-02 08:48:54.128564+00		28000	cash	Lunas		Kasir	100000	72000
TXN-20260602-6595	2026-06-02 09:10:37.490516+00		71000	qris	Lunas		Kasir	0	0
TXN-20260602-9930	2026-06-02 09:16:30.367742+00		81000	qris	Lunas		Kasir	0	0
TXN-20260602-2625	2026-06-02 08:59:11.019954+00		50000	qris	Lunas		Admin Utama	0	0
TXN-20260602-3027	2026-06-02 09:53:44.719146+00		43000	cash	Lunas		Kasir	50000	7000
TXN-20260602-3045	2026-06-02 09:58:22.357298+00		28000	cash	Lunas		Kasir	30000	2000
TXN-20260602-2195	2026-06-02 10:09:34.261925+00		51000	qris	Lunas		Kasir	0	0
TXN-20260602-8298	2026-06-02 10:14:24.140663+00		33000	qris	Lunas		Kasir	0	0
TXN-20260602-3421	2026-06-02 10:26:45.049033+00		36000	cash	Lunas		Kasir	50000	14000
TXN-20260602-3873	2026-06-02 10:50:36.750139+00		36000	cash	Lunas		Kasir	50000	14000
TXN-20260602-5674	2026-06-02 10:50:37.301587+00		36000	cash	Lunas		Kasir	50000	14000
TXN-20260602-4918	2026-06-02 11:02:28.2529+00		30000	cash	Lunas		Kasir	30000	0
TXN-20260602-1554	2026-06-02 11:03:02.132744+00		51000	qris	Lunas		Kasir	0	0
TXN-20260602-4567	2026-06-02 11:04:21.42315+00		28000	qris	Lunas		Kasir	0	0
TXN-20260602-4139	2026-06-02 11:11:08.940646+00		28000	cash	Lunas		Kasir	50000	22000
TXN-20260602-4541	2026-06-02 11:20:17.838402+00		94000	cash	Lunas		Kasir	100000	6000
TXN-20260602-1612	2026-06-02 11:53:24.429421+00		78000	qris	Lunas		Kasir	0	0
TXN-20260602-1123	2026-06-02 11:55:46.348645+00		46000	qris	Lunas		Kasir	0	0
TXN-20260602-1760	2026-06-02 12:14:03.189145+00		83000	cash	Lunas		Kasir	100000	17000
TXN-20260602-5453	2026-06-02 12:20:27.807805+00		140000	qris	Lunas		Kasir	0	0
TXN-20260602-5318	2026-06-02 12:20:28.698907+00		140000	qris	Lunas		Kasir	0	0
TXN-20260602-5272	2026-06-02 12:42:13.179171+00		23000	cash	Lunas		Kasir	50000	27000
TXN-20260602-2531	2026-06-02 12:42:13.679098+00		23000	cash	Lunas		Kasir	50000	27000
TXN-20260602-2010	2026-06-02 12:58:57.215148+00		23000	cash	Lunas		Kasir	25000	2000
TXN-20260602-2711	2026-06-02 13:16:02.92426+00		94000	cash	Lunas		Kasir	100000	6000
TXN-20260602-5783	2026-06-02 13:45:11.328447+00		60000	qris	Lunas		Kasir	0	0
TXN-20260602-7750	2026-06-02 14:49:14.390035+00		68000	qris	Lunas		Kasir	0	0
TXN-20260602-4843	2026-06-02 15:08:32.056166+00		54000	qris	Lunas		Kasir	0	0
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, name, username, password_hash, role, active, created_at, auth_id) FROM stdin;
1	Admin Utama	admin	$2a$10$mw2aVNUGorLGEAqx8vv8zuWpECtaeNkgzq0Lwp80mAv4z8T5/A/Ki	admin	t	2026-05-28 06:01:32.322785+00	a3472742-794a-4a36-bf07-e7bb6b6764e6
2	Kasir	kasir	$2a$10$HXgroAMNg4iOOZnetrBuSevUlEXXLi8I/WciRRbhkp24nQSBcG8rS	kasir	t	2026-05-28 06:01:32.322785+00	2148a101-12d9-4f5e-b13e-d09ceb9d7763
\.


--
-- Name: activity_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.activity_logs_id_seq', 114, true);


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.categories_id_seq', 10, true);


--
-- Name: product_variants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.product_variants_id_seq', 1, false);


--
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.products_id_seq', 62, true);


--
-- Name: transaction_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.transaction_items_id_seq', 117, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 8, true);


--
-- Name: activity_logs activity_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_logs
    ADD CONSTRAINT activity_logs_pkey PRIMARY KEY (id);


--
-- Name: categories categories_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: product_variants product_variants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_pkey PRIMARY KEY (id);


--
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (key);


--
-- Name: transaction_items transaction_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_logs_created_at ON public.activity_logs USING btree (created_at DESC);


--
-- Name: idx_users_auth_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_auth_id ON public.users USING btree (auth_id);


--
-- Name: product_variants product_variants_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_variants
    ADD CONSTRAINT product_variants_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- Name: transaction_items transaction_items_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id);


--
-- Name: transaction_items transaction_items_transaction_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE;


--
-- Name: users users_auth_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_auth_id_fkey FOREIGN KEY (auth_id) REFERENCES auth.users(id);


--
-- Name: transactions Akses penuh untuk user terautentikasi; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Akses penuh untuk user terautentikasi" ON public.transactions TO authenticated USING (true) WITH CHECK (true);


--
-- Name: users Allow authenticated to select users; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow authenticated to select users" ON public.users FOR SELECT TO authenticated USING (true);


--
-- Name: activity_logs Allow authenticated users to insert logs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow authenticated users to insert logs" ON public.activity_logs FOR INSERT TO authenticated, anon WITH CHECK (true);


--
-- Name: activity_logs Allow authenticated users to select logs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow authenticated users to select logs" ON public.activity_logs FOR SELECT TO authenticated USING (true);


--
-- Name: categories Allow public read access; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public read access" ON public.categories FOR SELECT TO authenticated, anon USING (true);


--
-- Name: users Allow users to update their own profile; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow users to update their own profile" ON public.users FOR UPDATE TO authenticated USING (((auth_id = auth.uid()) OR (username = split_part((auth.jwt() ->> 'email'::text), '@'::text, 1)))) WITH CHECK (((auth_id = auth.uid()) OR (username = split_part((auth.jwt() ->> 'email'::text), '@'::text, 1))));


--
-- Name: transaction_items Item transaksi aman; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Item transaksi aman" ON public.transaction_items TO authenticated USING (true) WITH CHECK (true);


--
-- Name: activity_logs Log hanya untuk internal; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Log hanya untuk internal" ON public.activity_logs TO authenticated USING (true) WITH CHECK (true);


--
-- Name: products Produk bisa dilihat semua orang; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Produk bisa dilihat semua orang" ON public.products FOR SELECT TO authenticated, anon USING (true);


--
-- Name: products Produk hanya bisa diubah Admin/User Login; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Produk hanya bisa diubah Admin/User Login" ON public.products TO authenticated USING (true) WITH CHECK (true);


--
-- Name: settings Settings aman; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Settings aman" ON public.settings TO authenticated USING (true) WITH CHECK (true);


--
-- Name: transactions Transaksi aman; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Transaksi aman" ON public.transactions TO authenticated USING (true) WITH CHECK (true);


--
-- PostgreSQL database dump complete
--

\unrestrict VWCfOMaTwqXJ1bX6ccW5ZwDOawZ94lTeMlGW7XxiHTlPhfbQM4DdwLgD9gSq7TL

