name: Supabase Daily Backup

on:
  schedule:
    - cron: '0 17 * * *' # Jam 00:00 WIB
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Backup Filename
        run: echo "BACKUP_FILENAME=backup_$(date +%Y-%m-%d).sql" >> $GITHUB_ENV

      - name: Dump Database via Docker
        env:
          PGPASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
          DB_HOST: ${{ secrets.SUPABASE_DB_HOST }}
          PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          if [ -z "$DB_HOST" ] || [ -z "$PGPASSWORD" ] || [ -z "$PROJECT_ID" ]; then
            echo "Error: Host, Password, atau Project ID belum diatur di GitHub Secrets!"
            exit 1
          fi
          mkdir -p backups
          docker run --rm \
            -e PGPASSWORD="$PGPASSWORD" \
            -v $(pwd)/backups:/backups \
            postgres:17 \
            pg_dump -h "$DB_HOST" -U "postgres.$PROJECT_ID" -d postgres -p 6543 --schema=public --no-owner --no-privileges -f /backups/${{ env.BACKUP_FILENAME }}

      - name: Commit and Push Backup
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Backup"
          git add backups/
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-backup: $(date +%Y-%m-%d)"
          git push

      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          filename: "backups/${{ env.BACKUP_FILENAME }}"
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "true"
